// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_VGfjwQRiLwjN1L06qgR_8TyYzSw_RRw',
    appId: '1:768818963112:web:ccb73e6975e1ab6643589d',
    messagingSenderId: '768818963112',
    projectId: 'shiftmate-df9ec',
    authDomain: 'shiftmate-df9ec.firebaseapp.com',
    databaseURL:
        'https://shiftmate-df9ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shiftmate-df9ec.firebasestorage.app',
    measurementId: 'G-2XF2Z17RYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJmC6mgYXkrNK1vJC-2Y7Cv9a4CgRu_U',
    appId: '1:768818963112:android:c814f69c0d7c830d43589d',
    messagingSenderId: '768818963112',
    projectId: 'shiftmate-df9ec',
    databaseURL:
        'https://shiftmate-df9ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shiftmate-df9ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYsYWGbA2dmqGTd-mlkrPfbbX8qqIHLmw',
    appId: '1:768818963112:ios:5eb9f442ca51e1c143589d',
    messagingSenderId: '768818963112',
    projectId: 'shiftmate-df9ec',
    databaseURL:
        'https://shiftmate-df9ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shiftmate-df9ec.firebasestorage.app',
    iosBundleId: 'com.example.shiftmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYsYWGbA2dmqGTd-mlkrPfbbX8qqIHLmw',
    appId: '1:768818963112:ios:5eb9f442ca51e1c143589d',
    messagingSenderId: '768818963112',
    projectId: 'shiftmate-df9ec',
    databaseURL:
        'https://shiftmate-df9ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shiftmate-df9ec.firebasestorage.app',
    iosBundleId: 'com.example.shiftmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_VGfjwQRiLwjN1L06qgR_8TyYzSw_RRw',
    appId: '1:768818963112:web:e08268a71059975843589d',
    messagingSenderId: '768818963112',
    projectId: 'shiftmate-df9ec',
    authDomain: 'shiftmate-df9ec.firebaseapp.com',
    databaseURL:
        'https://shiftmate-df9ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shiftmate-df9ec.firebasestorage.app',
    measurementId: 'G-DB1XK3EGED',
  );
}